### ISSUE TITLE
Getting token for a cert based automation connection does not work

### ISSUE THREAD

**Issue by stiglyt** [tyconsulting/AzureServicePrincipalAccount-PS#1]
When trying to get a token based on a Automation Account connection, it fails saying that the thumbprint is invalid. The problem seems to be that the script checks for the certificate at Cert:\LocalMachine\My, while Automation Accounts store the certificates at Cert:\CurrentUser\My. Could the script be changed to support both?

**Comment by michaelelleby** [comment]
I get the same issue, using version 2.0.0 in an Azure Automation Account PowerShell runbook:
```
$servicePrincipalConnection = Get-AutomationConnection -Name $connectionName
Add-AzAccount `
	-ServicePrincipal `
	-TenantId $servicePrincipalConnection.TenantId `
	-ApplicationId $servicePrincipalConnection.ApplicationId `
	-CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint

$AccessToken= Get-AzureADToken -AzureServicePrincipalConnection $servicePrincipalConnection
```
throws the error
```
System.Management.Automation.ValidationMetadataException: The variable cannot be validated because the value AB...... is not a valid value for the CertThumbprint variable.
	at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
	at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
	at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
	at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
	at System.Management.Automation.CommandProcessorBase.Complete()
